namespace GymChatAI.Application.Abstractions;

public record WhatsAppFlowTokenContext(Guid GymId, string ContactPhoneNumber, Guid FlowId);

/// <summary>
/// Correlates a flow_token (generated by us right before sending a Flow-trigger message)
/// back to the gym/contact/flow it belongs to. Needed because the Data Exchange endpoint's
/// decrypted payload carries only the flow_token - no phone number id or other context -
/// so this is the only way to know which gym's dynamic data (e.g. ClassTypes) to resolve,
/// and which Flow's screen graph to navigate. Short-lived by nature (a Flow session only
/// lasts as long as the user has it open), so an in-memory store is enough for now - would
/// need to move to persistent storage for a multi-instance deployment.
/// </summary>
public interface IWhatsAppFlowTokenStore
{
    string CreateToken(Guid gymId, string contactPhoneNumber, Guid flowId);

    WhatsAppFlowTokenContext? Resolve(string token);
}
