namespace GymChatAI.Application.Abstractions;

public record WhatsAppFlowTokenContext(Guid GymId, string ContactPhoneNumber);

/// <summary>
/// Correlates a flow_token (generated by us right before sending a Flow-trigger message)
/// back to the gym/contact it belongs to. Needed because the Data Exchange endpoint's
/// decrypted payload carries only the flow_token - no phone number id or other context -
/// so this is the only way to know, e.g., which gym's ClassTypes to return on "INIT".
/// Short-lived by nature (a Flow session only lasts as long as the user has it open), so an
/// in-memory store is enough for now - would need to move to persistent storage for a
/// multi-instance deployment.
/// </summary>
public interface IWhatsAppFlowTokenStore
{
    string CreateToken(Guid gymId, string contactPhoneNumber);

    WhatsAppFlowTokenContext? Resolve(string token);
}
