using GymChatAI.Domain.Common;
using GymChatAI.Domain.Enums;

namespace GymChatAI.Domain.Entities;

/// <summary>
/// A WhatsApp Flow (Meta's native multi-screen form experience) managed from the
/// Administration Portal - the richer alternative to the button/list-based
/// OnboardingFlowHandler, at the cost of requiring encryption + Business Verification.
/// Screens is the editable source of truth (built visually in the Flow Designer);
/// FlowJson is the compiled Meta-native JSON generated from it (see FlowJsonCompiler) -
/// kept in sync whenever ReplaceScreens is called.
/// </summary>
public class WhatsAppFlow : Entity
{
    private readonly List<FlowScreen> _screens = new();

    public Guid GymId { get; private set; }

    /// <summary>
    /// Snapshot of the gym's WhatsAppBusinessAccountId at creation time - lets the Portal
    /// filter out flows that belonged to a WABA the gym has since moved away from, without
    /// deleting the record. Null for flows created before this field existed.
    /// </summary>
    public string? WhatsAppBusinessAccountId { get; private set; }

    public string Name { get; private set; } = default!;

    /// <summary>Meta's own id for this flow, assigned once created via the API.</summary>
    public string? MetaFlowId { get; private set; }

    public WhatsAppFlowStatus Status { get; private set; } = WhatsAppFlowStatus.Draft;

    /// <summary>The compiled Flow JSON (screens/components), generated by FlowJsonCompiler from Screens.</summary>
    public string FlowJson { get; private set; } = "{}";

    /// <summary>
    /// Whether this flow needs live data at runtime (e.g. the gym's current class list) and
    /// therefore requires a Data Exchange endpoint. Explicitly set by whoever builds the
    /// flow - not auto-detected - so a purely static flow (fixed questions/options only)
    /// never has to configure or think about an endpoint at all. FlowJsonCompiler only
    /// emits "data_api_version" (the property that tells Meta an endpoint is required) when
    /// this is true.
    /// </summary>
    public bool IsDynamic { get; private set; }

    /// <summary>
    /// The Data Exchange endpoint URL registered with Meta for this flow. Only meaningful
    /// (and required before publishing) when IsDynamic is true. Stored locally - not just
    /// pushed to Meta - so the Portal can show what's already configured instead of always
    /// presenting an empty field.
    /// </summary>
    public string? EndpointUri { get; private set; }

    public IReadOnlyCollection<FlowScreen> Screens => _screens.AsReadOnly();

    private WhatsAppFlow() { }

    public WhatsAppFlow(Guid gymId, string name, string flowJson, string? whatsAppBusinessAccountId = null)
    {
        if (string.IsNullOrWhiteSpace(name))
            throw new ArgumentException("Flow name is required.", nameof(name));
        if (string.IsNullOrWhiteSpace(flowJson))
            throw new ArgumentException("Flow JSON is required.", nameof(flowJson));

        GymId = gymId;
        Name = name;
        FlowJson = flowJson;
        WhatsAppBusinessAccountId = whatsAppBusinessAccountId;
    }

    public void MarkCreated(string metaFlowId) => MetaFlowId = metaFlowId;

    public void UpdateFlowJson(string flowJson)
    {
        if (!string.IsNullOrWhiteSpace(flowJson)) FlowJson = flowJson;
        // Meta reverts a published flow to Draft whenever its assets change - mirror that here.
        if (Status == WhatsAppFlowStatus.Published) Status = WhatsAppFlowStatus.Draft;
        Touch();
    }

    /// <summary>
    /// Replaces the entire screen graph in one go - this is how the Flow Designer saves:
    /// it always sends the complete set of screens/components, not incremental diffs.
    /// Does NOT compile FlowJson itself (that's FlowJsonCompiler's job, in the Application
    /// layer, since it needs to resolve dynamic option sources like GymClassTypes) - call
    /// UpdateFlowJson afterwards with the compiled result.
    /// </summary>
    public void ReplaceScreens(IEnumerable<FlowScreen> screens)
    {
        _screens.Clear();
        _screens.AddRange(screens);
        Touch();
    }

    /// <summary>
    /// Marks whether this flow needs a Data Exchange endpoint. Switching from dynamic to
    /// static does NOT clear an already-configured EndpointUri - it's just ignored while
    /// IsDynamic is false, in case the flow gets marked dynamic again later.
    /// </summary>
    public void SetDynamic(bool isDynamic)
    {
        IsDynamic = isDynamic;
        Touch();
    }

    public void SetEndpointUri(string endpointUri)
    {
        if (string.IsNullOrWhiteSpace(endpointUri))
            throw new ArgumentException("Endpoint URL is required.", nameof(endpointUri));

        EndpointUri = endpointUri;
        Touch();
    }

    public void MarkPublished() => Status = WhatsAppFlowStatus.Published;

    public void MarkDeprecated() => Status = WhatsAppFlowStatus.Deprecated;

    public void SyncStatus(WhatsAppFlowStatus status) => Status = status;
}
